[package]
name = "minecraft-server-query"
version = "0.1.0"
authors = ["Jewoo Lee <shema7k@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
bstr = "0.2.13"
